GET http://localhost:3001/api/persons
Accept: application/json

###
GET http://localhost:3001/api/persons/667a85a8788f4d5cdedba192
Accept: application/json

###
GET http://localhost:3001/api/persons/5
Accept: application/json