GET http://localhost:3001/api/people
Accept: application/json

###
GET http://localhost:3001/api/people/667a85a8788f4d5cdedba192
Accept: application/json

###
GET http://localhost:3001/api/people/5
Accept: application/json