POST http://localhost:3001/api/people
Content-Type: application/json

{
  "name": "Shiqi Gong",
  "number": "23-13-3124122"
}

###
POST http://localhost:3001/api/people
Content-Type: application/json

{
  "name": "122222",
  "number": "23-13-3124122"
}

###